package constants

import "github.com/scientist-v08/bphs/models"

type HouseMappings map[models.AllRaashis]int16
type ReverseHouseMappings map[int16]models.AllRaashis
type NumericalAscendantHousesMap map[string]HouseMappings
type ReverseNumericalAscendantHousesMap map[string]ReverseHouseMappings

const (
	Mesha models.AllRaashis =  "Mesha"
	SuryaUccha models.AllRaashis =  "Mesha"
	ShaniNeecha models.AllRaashis =  "Mesha"
	Vrushabha models.AllRaashis =  "Vrushabha"
	ChandraUccha models.AllRaashis =  "Vrushabha"
	Mithuna models.AllRaashis =  "Mithuna"
	Karkataka models.AllRaashis =  "Karkataka"
	GuruUccha models.AllRaashis =  "Karkataka"
	KujaNeecha models.AllRaashis =  "Karkataka"
	Simha models.AllRaashis =  "Simha"
	Kanya models.AllRaashis =  "Kanya"
	BudhaUccha models.AllRaashis =  "Kanya"
	ShukraNeecha models.AllRaashis =  "Kanya"
	Tula models.AllRaashis =  "Tula"
	ShaniUccha models.AllRaashis =  "Tula"
	SuryaNeecha models.AllRaashis =  "Tula"
	Vruschika models.AllRaashis =  "Vruschika"
	ChandraNeecha models.AllRaashis =  "Vruschika"
	Dhanassu models.AllRaashis =  "Dhanassu"
	Makara models.AllRaashis =  "Makara"
	KujaUccha models.AllRaashis =  "Makara"
	GuruNeecha models.AllRaashis =  "Makara"
	Kumbha models.AllRaashis =	 "Kumbha"
	Meena models.AllRaashis =  "Meena"
	BudhaNeecha models.AllRaashis =  "Meena"
	ShukraUccha models.AllRaashis =  "Meena"
)

var NumericalMappingsStore = NumericalAscendantHousesMap{
    "Mesha": {
        Mesha: 1,
        Vrushabha: 2,
        Mithuna: 3,
        Karkataka: 4,
        Simha: 5,
        Kanya: 6,
        Tula: 7,
        Vruschika: 8,
        Dhanassu: 9,
        Makara: 10,
        Kumbha: 11,
        Meena: 12,
    },
    "Vrushabha": {
        Mesha: 12,
        Vrushabha: 1,
        Mithuna: 2,
        Karkataka: 3,
        Simha: 4,
        Kanya: 5,
        Tula: 6,
        Vruschika: 7,
        Dhanassu: 8,
        Makara: 9,
        Kumbha: 10,
        Meena: 11,
    },
    "Mithuna": {
        Mesha: 11,
        Vrushabha: 12,
        Mithuna: 1,
        Karkataka: 2,
        Simha: 3,
        Kanya: 4,
        Tula: 5,
        Vruschika: 6,
        Dhanassu: 7,
        Makara: 8,
        Kumbha: 9,
        Meena: 10,
    },
    "Karkataka": {
        Mesha: 10,
        Vrushabha: 11,
        Mithuna: 12,
        Karkataka: 1,
        Simha: 2,
        Kanya: 3,
        Tula: 4,
        Vruschika: 5,
        Dhanassu: 6,
        Makara: 7,
        Kumbha: 8,
        Meena: 9,
    },
    "Simha": {
        Mesha: 9,
        Vrushabha: 10,
        Mithuna: 11,
        Karkataka: 12,
        Simha: 1,
        Kanya: 2,
        Tula: 3,
        Vruschika: 4,
        Dhanassu: 5,
        Makara: 6,
        Kumbha: 7,
        Meena: 8,
    },
    "Kanya": {
        Mesha: 8,
        Vrushabha: 9,
        Mithuna: 10,
        Karkataka: 11,
        Simha: 12,
        Kanya: 1,
        Tula: 2,
        Vruschika: 3,
        Dhanassu: 4,
        Makara: 5,
        Kumbha: 6,
        Meena: 7,
    },
    "Tula": {
        Mesha: 7,
        Vrushabha: 8,
        Mithuna: 9,
        Karkataka: 10,
        Simha: 11,
        Kanya: 12,
        Tula: 1,
        Vruschika: 2,
        Dhanassu: 3,
        Makara: 4,
        Kumbha: 5,
        Meena: 6,
    },
    "Vruschika": {
        Mesha: 6,
        Vrushabha: 7,
        Mithuna: 8,
        Karkataka: 9,
        Simha: 10,
        Kanya: 11,
        Tula: 12,
        Vruschika: 1,
        Dhanassu: 2,
        Makara: 3,
        Kumbha: 4,
        Meena: 5,
    },
    "Dhanassu": {
        Mesha: 5,
        Vrushabha: 6,
        Mithuna: 7,
        Karkataka: 8,
        Simha: 9,
        Kanya: 10,
        Tula: 11,
        Vruschika: 12,
        Dhanassu: 1,
        Makara: 2,
        Kumbha: 3,
        Meena: 4,
    },
    "Makara": {
        Mesha: 4,
        Vrushabha: 5,
        Mithuna: 6,
        Karkataka: 7,
        Simha: 8,
        Kanya: 9,
        Tula: 10,
        Vruschika: 11,
        Dhanassu: 12,
        Makara: 1,
        Kumbha: 2,
        Meena: 3,
    },
    "Kumbha": {
        Mesha: 3,
        Vrushabha: 4,
        Mithuna: 5,
        Karkataka: 6,
        Simha: 7,
        Kanya: 8,
        Tula: 9,
        Vruschika: 10,
        Dhanassu: 11,
        Makara: 12,
        Kumbha: 1,
        Meena: 2,
    },
    "Meena": {
        Mesha: 2,
        Vrushabha: 3,
        Mithuna: 4,
        Karkataka: 5,
        Simha: 6,
        Kanya: 7,
        Tula: 8,
        Vruschika: 9,
        Dhanassu: 10,
        Makara: 11,
        Kumbha: 12,
        Meena: 1,
    },
}

var ReverseNumericalMappingsStore = ReverseNumericalAscendantHousesMap{
    "Mesha": {
        1: Mesha,
        2: Vrushabha,
        3: Mithuna,
        4: Karkataka,
        5: Simha,
        6: Kanya,
        7: Tula,
        8: Vruschika,
        9: Dhanassu,
        10: Makara,
        11: Kumbha,
        12: Meena,
    },
    "Vrushabha": {
        12: Mesha,
        1: Vrushabha,
        2: Mithuna,
        3: Karkataka,
        4: Simha,
        5: Kanya,
        6: Tula,
        7: Vruschika,
        8: Dhanassu,
        9: Makara,
        10: Kumbha,
        11: Meena,
    },
    "Mithuna": {
        11: Mesha,
        12: Vrushabha,
        1: Mithuna,
        2: Karkataka,
        3: Simha,
        4: Kanya,
        5: Tula,
        6: Vruschika,
        7: Dhanassu,
        8: Makara,
        9: Kumbha,
        0: Meena,
    },
    "Karkataka": {
        10: Mesha,
        11: Vrushabha,
        12: Mithuna,
        1: Karkataka,
        2: Simha,
        3: Kanya,
        4: Tula,
        5: Vruschika,
        6: Dhanassu,
        7: Makara,
        8: Kumbha,
        9: Meena,
    },
    "Simha": {
        9: Mesha,
        10: Vrushabha,
        11: Mithuna,
        12: Karkataka,
        1: Simha,
        2: Kanya,
        3: Tula,
        4: Vruschika,
        5: Dhanassu,
        6: Makara,
        7: Kumbha,
        8: Meena,
    },
    "Kanya": {
        8: Mesha,
        9: Vrushabha,
        10: Mithuna,
        11: Karkataka,
        12: Simha,
        1: Kanya,
        2: Tula,
        3: Vruschika,
        4: Dhanassu,
        5: Makara,
        6: Kumbha,
        7: Meena,
    },
    "Tula": {
        7: Mesha,
        8: Vrushabha,
        9: Mithuna,
        10: Karkataka,
        11: Simha,
        12: Kanya,
        1: Tula,
        2: Vruschika,
        3: Dhanassu,
        4: Makara,
        5: Kumbha,
        6: Meena,
    },
    "Vruschika": {
        6: Mesha,
        7: Vrushabha,
        8: Mithuna,
        9: Karkataka,
        10: Simha,
        11: Kanya,
        12: Tula,
        1: Vruschika,
        2: Dhanassu,
        3: Makara,
        4: Kumbha,
        5: Meena,
    },
    "Dhanassu": {
        5: Mesha,
        6: Vrushabha,
        7: Mithuna,
        8: Karkataka,
        9: Simha,
        10: Kanya,
        11: Tula,
        12: Vruschika,
        1: Dhanassu,
        2: Makara,
        3: Kumbha,
        4: Meena,
    },
    "Makara": {
        4: Mesha,
        5: Vrushabha,
        6: Mithuna,
        7: Karkataka,
        8: Simha,
        9: Kanya,
        10: Tula,
        11: Vruschika,
        12: Dhanassu,
        1: Makara,
        2: Kumbha,
        3: Meena,
    },
    "Kumbha": {
        3: Mesha,
        4: Vrushabha,
        5: Mithuna,
        6: Karkataka,
        7: Simha,
        8: Kanya,
        9: Tula,
        10: Vruschika,
        11: Dhanassu,
        12: Makara,
        1: Kumbha,
        2: Meena,
    },
    "Meena": {
        2: Mesha,
        3: Vrushabha,
        4: Mithuna,
        5: Karkataka,
        6: Simha,
        7: Kanya,
        8: Tula,
        9: Vruschika,
        10: Dhanassu,
        11: Makara,
        12: Kumbha,
        1: Meena,
    },
}