package constants

import "github.com/scientist-v08/bphs/models"

type AscendantToRashyadhipatiMap map[models.AllRaashis]map[models.Raashyadhipati][]int8

var AscendantToRashyadhipatiMapStore = AscendantToRashyadhipatiMap{
	Mesha: {
		Surya: {int8(5)},
		Chandra: {int8(4)},
		Kuja: {int8(1), int8(8)},
		Budha: {int8(3), int8(6)},
		Guru: {int8(9), int8(12)},
		Shukra: {int8(2), int8(7)},
		Shani: {int8(10), int8(11)},
	},
	Vrushabha: {
        Surya:   {4},
        Chandra: {3},
        Kuja:    {7, 12},
        Budha:   {2, 5},
        Guru:    {8, 11},
        Shukra:  {1, 6},
        Shani:   {9, 10},
    },
    Mithuna: {
        Surya:   {3},
        Chandra: {2},
        Kuja:    {6, 11},
        Budha:   {1, 4},
        Guru:    {7, 10},
        Shukra:  {5, 12},
        Shani:   {8, 9},
    },
    Karkataka: {
        Surya:   {2},
        Chandra: {1},
        Kuja:    {5, 10},
        Budha:   {3, 12},
        Guru:    {6, 9},
        Shukra:  {4, 11},
        Shani:   {7, 8},
    },
    Simha: {
        Surya:   {1},
        Chandra: {12},
        Kuja:    {4, 9},
        Budha:   {2, 11},
        Guru:    {5, 8},
        Shukra:  {3, 10},
        Shani:   {6, 7},
    },
    Kanya: {
        Surya:   {12},
        Chandra: {11},
        Kuja:    {3, 8},
        Budha:   {1, 10},
        Guru:    {4, 7},
        Shukra:  {2, 9},
        Shani:   {5, 6},
    },
    Tula: {
        Surya:   {11},
        Chandra: {10},
        Kuja:    {2, 7},
        Budha:   {9, 12},
        Guru:    {3, 6},
        Shukra:  {1, 8},
        Shani:   {4, 5},
    },
    Vruschika: {
        Surya:   {10},
        Chandra: {9},
        Kuja:    {1, 6},
        Budha:   {8, 11},
        Guru:    {2, 5},
        Shukra:  {7, 12},
        Shani:   {3, 4},
    },
    Dhanassu: {
        Surya:   {9},
        Chandra: {8},
        Kuja:    {5, 12},
        Budha:   {7, 10},
        Guru:    {1, 4},
        Shukra:  {6, 11},
        Shani:   {2, 3},
    },
    Makara: {
        Surya:   {8},
        Chandra: {7},
        Kuja:    {4, 11},
        Budha:   {6, 9},
        Guru:    {3, 12},
        Shukra:  {5, 10},
        Shani:   {1, 2},
    },
    Kumbha: {
        Surya:   {7},
        Chandra: {6},
        Kuja:    {3, 10},
        Budha:   {5, 8},
        Guru:    {2, 11},
        Shukra:  {4, 9},
        Shani:   {1, 12},
    },
    Meena: {
        Surya:   {6},
        Chandra: {5},
        Kuja:    {2, 9},
        Budha:   {4, 7},
        Guru:    {1, 10},
        Shukra:  {3, 8},
        Shani:   {11, 12},
    },
}